### ISSUE TITLE
Program fails to open on macOS

### ISSUE THREAD

**Issue by prateekma** [wpilibsuite/frc-characterization#152]
```
Python(55883,0x111345e00) malloc: can't allocate region
:*** mach_vm_map(size=18446744072038682624, flags: 100) failed (error code=3)
Python(55883,0x111345e00) malloc: *** set a breakpoint in malloc_error_break to debug
init_dgelsd failed init
Traceback (most recent call last):
  File "/usr/local/bin/frc-characterization", line 5, in <module>
    from frc_characterization.cli import main
  File "/usr/local/lib/python3.8/site-packages/frc_characterization/cli/__init__.py", line 10, in <module>
    import frc_characterization.logger_analyzer.data_analyzer as analyzer
  File "/usr/local/lib/python3.8/site-packages/frc_characterization/logger_analyzer/data_analyzer.py", line 15, in <module>
    import control as cnt
  File "/usr/local/lib/python3.8/site-packages/control/__init__.py", line 49, in <module>
    from .bdalg import *
  File "/usr/local/lib/python3.8/site-packages/control/bdalg.py", line 56, in <module>
    import numpy as np
  File "/usr/local/lib/python3.8/site-packages/numpy/__init__.py", line 286, in <module>
    raise RuntimeError(msg)
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
RankWarning: Polyfit may be poorly conditioned
```

macOS 11.0.1
Python 3.8.6
NumPy 1.19.4

**Comment by sciencewhiz** [comment]
https://github.com/numpy/numpy/issues/15947
