### ISSUE TITLE
[CRASH] IsADirectoryError: logger_analyzer/templates

### ISSUE THREAD

**Issue by RyanHir** [wpilibsuite/frc-characterization#158]
Fresh installation on Arch Linux using guide from https://docs.wpilib.org/en/stable/docs/software/wpilib-tools/robot-characterization/introduction.html

Extra package installed from the repos `tk`

When running `frc-characterization drive new` per documentation instructions, I receive this error...

```
Traceback (most recent call last):
  File "/home/ryan/.local/bin/frc-characterization", line 8, in <module>
    sys.exit(main())
  File "/home/ryan/.local/lib/python3.9/site-packages/frc_characterization/cli/__init__.py", line 97, in main
    tool_dict[args.mech_type][args.tool_type](directory=args.project_directory)
  File "/home/ryan/.local/lib/python3.9/site-packages/frc_characterization/cli/__init__.py", line 25, in new_project
    newproject.main(testType)
  File "/home/ryan/.local/lib/python3.9/site-packages/frc_characterization/newproject/__init__.py", line 498, in main
    project.configureGUI()
  File "/home/ryan/.local/lib/python3.9/site-packages/frc_characterization/newproject/__init__.py", line 389, in configureGUI
    updateTemplatePath()
  File "/home/ryan/.local/lib/python3.9/site-packages/frc_characterization/newproject/__init__.py", line 121, in updateTemplatePath
    with resources.path(mech, "templates") as path:
  File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.9/importlib/resources.py", line 175, in _path_from_reader
    opener_reader = reader.open_resource(norm_resource)
  File "<frozen importlib._bootstrap_external>", line 995, in open_resource
IsADirectoryError: [Errno 21] Is a directory: '/home/ryan/.local/lib/python3.9/site-packages/frc_characterization/logger_analyzer/templates'
```

**Comment by calcmogul** [comment]
I had that same error on Arch yesterday, and someone else reproduced it on macOS. It doesn't seem to occur on Windows. We have no idea why it happens yet.

**Comment by RyanHir** [comment]
Noted, will use a windows machine for the meantime.
